//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentRequest
    {
        public int SNo { get; set; }
        public string UserName { get; set; }
        public short CourseID { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
