//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public short TestID { get; set; }
        public string UserName { get; set; }
        public Nullable<short> CourseID { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<decimal> TestPercentage { get; set; }
        public string TestRemarks { get; set; }
        public Nullable<bool> Certificate { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
